# docker-compose.yml文件的版本
version: "3"
# 管理的服务
services:
  web:
    build: .
    volumes:
      - /zhc:/test
    command: java -jar /test/test.jar
    image: "java:8"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
  redis:
    # 指定镜像
    image: redis:4
    ports:
      # 端口映射
      - 6379:6379
    volumes:
      # 目录映射
      - "./redis/conf:/usr/local/etc/redis"
      - "./redis/data:/data"
    command:
      # 执行的命令
      redis-server

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - "/zhc/mysql/conf:/etc/mysql/conf.d"
      - "/zhc/mysql/logs:/logs"
      - "/zhc/mysql/data:/var/lib/mysql"
    environment:
      # 环境变量
      - MYSQL_ROOT_PASSWORD="123456"
      - MYSQL_DATABASE="demo"